### ISSUE TITLE
How do I include the form contents in the notification that's sent to the user?

### ISSUE THREAD

**Issue by j-greig** [googlesamples/apps-script-form-notifications-addon#1]

**Comment by ryan-devrel** [comment]
This add-on wasn't designed to do that, but you can adapt it. The function that handles the form submit trigger event is sent a FormResponse object as a parameter:

https://developers.google.com/apps-script/guides/triggers/events#google_forms_events

To do what you're asking, you would just need to query that FormResponse object for the information the user provided and include that in the notification email.
