### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by mbrukman** [googlesamples/apps-script-form-notifications-addon#10]
The edit dialog where I can set my notifications includes the following HTML at the bottom left of the pop-up:

    <img alt="Add-on logo" class="logo" width="25"
    src="https://googledrive.com/host/0B0G1UdyJGrY6XzdjQWF4a1JYY1k/form-notifications-logo-small.png">

Unfortunately, because this image URL is invalid, it just shows up as a broken image rather than what presumably should be there, which is perhaps something like this (from the [web store landing page](https://chrome.google.com/webstore/detail/form-notifications/bbpdeojefjfhaelgljjcadpcckdfcdod)):

![Form Notifications logo](https://lh3.googleusercontent.com/wNu9QHoYPU3jJihA1n3gLPAE5yb6vpxIcyIgAfmjGyxeIRZVF8oaoJ92bKD1c3i5T7YCU7wzkw=s50-h50-e365-rw)

**Comment by ryan-devrel** [comment]
Fixed.
