### ISSUE TITLE
Add reply adress?

### ISSUE THREAD

**Issue by ghost** [googlesamples/apps-script-form-notifications-addon#2]
Is it possible to add an reply adress in the de addon so that I can set an reply-to (sender) adress that recievers will see (Notify respondents)?

**Comment by ryan-devrel** [comment]
In MailApp.sendEmail(), you can include a 'replyTo' email as a parameter that will be used as the default reply-to address. See:

https://developers.google.com/apps-script/reference/mail/mail-app#sendEmail(String,String,String,Object)
