### ISSUE TITLE
Add-on no longer display correct text in menus

### ISSUE THREAD

**Issue by tohagan** [googlesamples/apps-script-form-notifications-addon#6]
I've just spun up this app-script-form-notification-addon with zero code changes including this code:

function onOpen(e) {
  FormApp.getUi()
      .createAddonMenu()
      .addItem('Configure notifications', 'showSidebar')
      .addItem('About', 'showAbout')
      .addToUi();
}

Both menu items execute showSidebar() and showAbout() but the menu text displayed does not match this code?!.  Instead, I'm seeing the addon name appear ... 

![gforms1](https://cloud.githubusercontent.com/assets/301525/13526398/669ae74a-e253-11e5-8f56-11247bb44d00.png)

![gforms2](https://cloud.githubusercontent.com/assets/301525/13526401/6b80ddc8-e253-11e5-8d19-8f0a93a0ce39.png)

**Comment by tohagan** [comment]
I noticed that there was a version change to Google Forms so perhaps that might the cause.

**Comment by erickoledadevrel** [comment]
Yes, this is due to a bug with the latest release of Google Forms. I've raised the issue with the engineering team.
